const EVE_TRADE_PLUS_DOMAIN = import.meta.env.VITE_EVE_TRADE_PLUS_DOMAIN;
const EVE_TRADE_PLUS_WEBSOCKET_DOMAIN = import.meta.env
  .VITE_EVE_TRADE_PLUS_WEBSOCKET_DOMAIN;
const DEVELOPMENT = import.meta.env.DEV;
const PRODUCTION = import.meta.env.PROD;

export {
  EVE_TRADE_PLUS_DOMAIN,
  EVE_TRADE_PLUS_WEBSOCKET_DOMAIN,
  DEVELOPMENT,
  PRODUCTION,
};
