const EVE_TRADE_PLUS_DOMAIN = import.meta.env.VITE_EVE_TRADE_PLUS_DOMAIN;
const EVE_TRADE_PLUS_WEBSOCKET_DOMAIN = import.meta.env
  .VITE_EVE_TRADE_PLUS_WEBSOCKET_DOMAIN;
const DEVELOPMENT = import.meta.env.DEV;
const PRODUCTION = import.meta.env.PROD;
const INQUIRIES_EMAIL = import.meta.env.VITE_INQUIRIES_EMAIL;
const WEBSITE_NAME = import.meta.env.VITE_WEBSITE_NAME;

export {
  EVE_TRADE_PLUS_DOMAIN,
  EVE_TRADE_PLUS_WEBSOCKET_DOMAIN,
  INQUIRIES_EMAIL,
  WEBSITE_NAME,
  DEVELOPMENT,
  PRODUCTION,
};
