const EVE_TRADE_PLUS_DOMAIN = import.meta.env.VITE_EVE_TRADE_PLUS_DOMAIN;
const EVE_TRADE_PLUS_WEBSOCKET_DOMAIN = import.meta.env
  .VITE_EVE_TRADE_PLUS_WEBSOCKET_DOMAIN;

export { EVE_TRADE_PLUS_DOMAIN, EVE_TRADE_PLUS_WEBSOCKET_DOMAIN };
